const {_electron}=require('playwright-core');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{const executable=process.argv[2];
const app=await _electron.launch({executablePath:executable||require('electron'),args:executable?['--verify']:[path.resolve(__dirname,'..'),'--verify'],timeout:60000});try{const p=await app.firstWindow();
const errors=[];
    p.on('pageerror',e=>errors.push(e.message));
    await p.waitForLoadState('load');
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.session.enableNetworkEmulation({offline:true}));
    await p.reload();
    await p.waitForFunction(()=>window.Globe&&Globe.ready());
    await p.addStyleTag({content:'*{transition:none!important}#page-fade{display:none!important}'});
    assert.equal(await p.locator('#sec-story, #sec-monitoring, #home-btn').count(),0);
    assert.equal(await p.evaluate(()=>typeof window.Shell),'undefined');
    assert.equal(await p.evaluate(()=>typeof window.require),'undefined');
    await p.waitForFunction(()=>document.querySelector('#reset-view-icon')?.naturalWidth===36);
    await p.locator('#reset-view').click();
    await p.getByRole('button',{name:'2015',exact:true}).click();
    assert((await p.locator('#news-list').innerText()).includes('Требования стран-импортёров'));
    await p.locator('#search').fill('Турция');
    await p.locator('#country-list .country-row').filter({hasText:'Турция'}).first().click();
    await p.waitForFunction(()=>document.querySelector('#sec-globe').classList.contains('is-country'));
    await p.locator('#back-map').click();
    await p.waitForFunction(()=>document.querySelector('#sec-globe').classList.contains('is-map'));
const blocked=await app.evaluate(async({BrowserWindow})=>{try{await BrowserWindow.getAllWindows()[0].webContents.session.fetch('https://example.com');return false;}catch{return true;}});
    assert(blocked);
const prefs=await app.evaluate(({BrowserWindow})=>{const p=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();return {sandbox:p.sandbox,contextIsolation:p.contextIsolation,nodeIntegration:p.nodeIntegration};});
    assert.deepEqual(prefs,{sandbox:true,contextIsolation:true,nodeIntegration:false});
    assert.deepEqual(errors,[]);
    console.log('PASS standalone export: direct globe startup, no menu/other pages, years, country search/back, reset and offline operation');}finally{await app.close();}})().catch(e=>{console.error(e);process.exitCode=1});
